# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages_final.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'messages_final.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14messages_final.proto\x12\x07sensors\"\x82\x01\n\nSensorData\x12\x0e\n\x06Tensao\x18\x01 \x03(\x02\x12\x10\n\x08\x43orrente\x18\x02 \x03(\x02\x12\x10\n\x08Potencia\x18\x03 \x03(\x02\x12\x0f\n\x07\x45nergia\x18\x04 \x03(\x02\x12\x10\n\x08\x46\x61torPot\x18\x05 \x03(\x02\x12\r\n\x05\x42loco\x18\x06 \x01(\t\x12\x0e\n\x06\x45stado\x18\x07 \x01(\x05\"N\n\nDeviceInfo\x12\x0c\n\x04TIPO\x18\x01 \x01(\t\x12\r\n\x05\x42LOCO\x18\x02 \x01(\t\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x17\n\x0fPORTA_ENVIO_TCP\x18\x04 \x01(\x05\"P\n\x0bGatewayInfo\x12\x0c\n\x04TIPO\x18\x01 \x01(\t\x12\x0e\n\x06GTW_ID\x18\x02 \x01(\x05\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x17\n\x0fPORTA_ENVIO_UDP\x18\x04 \x01(\x05\"@\n\x14SensorDataCollection\x12(\n\x0bsensor_data\x18\x01 \x03(\x0b\x32\x13.sensors.SensorData\"\xb5\x01\n\x07\x43ommand\x12,\n\x0creceive_data\x18\x01 \x01(\x0b\x32\x14.sensors.ReceiveDataH\x00\x12&\n\tset_state\x18\x02 \x01(\x0b\x32\x11.sensors.SetStateH\x00\x12\x1d\n\x04list\x18\x03 \x01(\x0b\x32\r.sensors.ListH\x00\x12*\n\x0b\x63heck_state\x18\x04 \x01(\x0b\x32\x13.sensors.CheckStateH\x00\x42\t\n\x07payload\"\r\n\x0bReceiveData\"+\n\x08SetState\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x08\"\x1c\n\x04List\x12\x14\n\x0clist_request\x18\x01 \x01(\t\"\x1e\n\nCheckState\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"2\n\nDeviceList\x12$\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x13.sensors.DeviceInfo\"0\n\x06Sensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\".\n\nSensorList\x12 \n\x07sensors\x18\x01 \x03(\x0b\x32\x0f.sensors.Sensor\" \n\x0bStateChange\x12\x11\n\tnew_state\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_final_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=34
  _globals['_SENSORDATA']._serialized_end=164
  _globals['_DEVICEINFO']._serialized_start=166
  _globals['_DEVICEINFO']._serialized_end=244
  _globals['_GATEWAYINFO']._serialized_start=246
  _globals['_GATEWAYINFO']._serialized_end=326
  _globals['_SENSORDATACOLLECTION']._serialized_start=328
  _globals['_SENSORDATACOLLECTION']._serialized_end=392
  _globals['_COMMAND']._serialized_start=395
  _globals['_COMMAND']._serialized_end=576
  _globals['_RECEIVEDATA']._serialized_start=578
  _globals['_RECEIVEDATA']._serialized_end=591
  _globals['_SETSTATE']._serialized_start=593
  _globals['_SETSTATE']._serialized_end=636
  _globals['_LIST']._serialized_start=638
  _globals['_LIST']._serialized_end=666
  _globals['_CHECKSTATE']._serialized_start=668
  _globals['_CHECKSTATE']._serialized_end=698
  _globals['_DEVICELIST']._serialized_start=700
  _globals['_DEVICELIST']._serialized_end=750
  _globals['_SENSOR']._serialized_start=752
  _globals['_SENSOR']._serialized_end=800
  _globals['_SENSORLIST']._serialized_start=802
  _globals['_SENSORLIST']._serialized_end=848
  _globals['_STATECHANGE']._serialized_start=850
  _globals['_STATECHANGE']._serialized_end=882
# @@protoc_insertion_point(module_scope)
