# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x82\x01\n\nSensorData\x12\x0e\n\x06Tensao\x18\x01 \x03(\x02\x12\x10\n\x08\x43orrente\x18\x02 \x03(\x02\x12\x10\n\x08Potencia\x18\x03 \x03(\x02\x12\x0f\n\x07\x45nergia\x18\x04 \x03(\x02\x12\x10\n\x08\x46\x61torPot\x18\x05 \x03(\x02\x12\r\n\x05\x42loco\x18\x06 \x01(\t\x12\x0e\n\x06\x45stado\x18\x07 \x01(\x05\"N\n\nDeviceInfo\x12\x0c\n\x04TIPO\x18\x01 \x01(\t\x12\r\n\x05\x42LOCO\x18\x02 \x01(\t\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x17\n\x0fPORTA_ENVIO_TCP\x18\x04 \x01(\x05\"P\n\x0bGatewayInfo\x12\x0c\n\x04TIPO\x18\x01 \x01(\t\x12\x0e\n\x06GTW_ID\x18\x02 \x01(\x05\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x17\n\x0fPORTA_ENVIO_UDP\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORDATA._serialized_start=19
  _SENSORDATA._serialized_end=149
  _DEVICEINFO._serialized_start=151
  _DEVICEINFO._serialized_end=229
  _GATEWAYINFO._serialized_start=231
  _GATEWAYINFO._serialized_end=311
# @@protoc_insertion_point(module_scope)
